### ISSUE TITLE
DeviceInfoHandler::BuildReported faild

### ISSUE THREAD

**Issue by v-jiq** [ms-iot/azure-client-tools#19]
Hi,
          When  DeviceInfoPlugin.dll runs to DeviceInfoHandler::OnConnectionStatusChanged will occur error and  below is log message:
![1553838409(1)](https://user-images.githubusercontent.com/39880470/55212015-34885f00-5229-11e9-88a4-64f5cbee9f43.png)

According to log message,I know that the program error is due to it can't get xml file. 
but I  don't know what should  I do for resolve the problem.

Thanks.

**Comment by gmileka** [comment]
Hi v-jiq,

This problem occurs because Embedded Mode is not turned on on the machine where the device agent is running. I assume you are running this on the desktop?

To enable Embedded Mode, please, follow the instructions here:
https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/embeddedmode

thanks,
george

**Comment by gmileka** [comment]
Hi v-jiq, please, re-open the issue if you're seeing a problem.
